image: rust:slim-stretch

before_script:
  - apt-get update
  - apt-get install mingw-w64 build-essential -y
  - mkdir ~/.cargo -p
  - rustup target add x86_64-pc-windows-gnu
  - rustup default nightly
  - rustup component add rustfmt
  - rustup component add clippy
  - echo -e '\n[target.x86_64-pc-windows-gnu]\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-gcc-ar"' >> ~/.cargo/config.toml
  - rustc --version && cargo --version && rustup toolchain list  # Print version info for debugging

stages:
  - lint
  - test
  - deploy

cargo:fmt:
  stage: lint
  script: cargo fmt -v -- --check

cargo:clippy: 
  stage: lint
  script: cargo clippy -v --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu -Zmultitarget

cargo:check:
  stage: lint
  script: cargo check -v --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu -Zmultitarget

cargo:test: 
  script: cargo test -v

examples:
  stage: deploy
  script:
    - cargo build -v --release --examples --out-dir build -Zunstable-options --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu -Zmultitarget
  artifacts:
    paths:
      - build