image: rust:slim-stretch

before_script:
  - apt-get update
  - apt-get install mingw-w64 build-essential -y
  - mkdir ~/.cargo -p
  - rustup target add x86_64-pc-windows-gnu
  - echo -e '\n[target.x86_64-pc-windows-gnu]\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-gcc-ar"' >> ~/.cargo/config.toml
  - rustc --version && cargo --version  # Print version info for debugging

stages:
  - format
  - lint
  - check
  - test
  - deploy

rustfmt:
  stage: format
  script: cargo fmt -v -- --check

cargo-clippy-unix: 
  stage: lint
  script: cargo clippy -v
cargo-clippy-windows:
  stage: lint
  script: cargo clippy -v --target x86_64-pc-windows-gnu

cargo-check-unix:
  stage: check
  script: cargo check -v 
cargo-check-windows: 
  stage: check
  script: cargo check -v --target x86_64-pc-windows-gnu

cargo-test: 
  script: cargo test -v

amiroot-unix:
  stage: deploy
  script:
    - cargo build --release --example amiroot
    - mv target/release/examples/amiroot .
  artifacts:
    paths:
      - amiroot

amiroot-windows:
  stage: deploy
  script:
    - cargo build --release --example amiroot --target x86_64-pc-windows-gnu
    - mv target/x86_64-pc-windows-gnu/release/examples/amiroot.exe .
  artifacts:
    paths:
      - amiroot.exe
