[package]
name = "is-root"
version = "0.1.0"
authors = ["John Meow <j0hn.meow@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(unix)'.dependencies]
users = "0.10"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
default-features = false
features = ["minwindef", "handleapi", "processthreadsapi", "securitybaseapi"]
